language: node_js
node_js: "12"
os:
- linux
- osx
dist: trusty
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

install:
- npm install

script:
- npm run test:ci

after_success: if test -n "$TRAVIS_TAG"; then fi;
