name: Node CI

on:
  push:
    branches:
      - master
      - /^v\d+\.\d+\.\d+/

jobs:
  test_and_coverage:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['12']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
        env:
          CI: true
      - name: Test in CI
        run: npm run test:ci
        env:
          CI: true
      - name: Show coverage
        if: matrix.os == 'ubuntu-latest'
        run: npm run test:coverage
        env:
          CI: true
